sudo: false

language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps-test
  - go get -v github.com/mattn/goveralls
  - npm install -g codeclimate-test-reporter

install:
  - wget http://download.redis.io/releases/redis-stable.tar.gz
  - tar xf redis-stable.tar.gz
  - (cd redis-stable && make)
  - export PATH=./redis-stable/src:$PATH
  - redis-server --version
  - redis-server .travis/redis.conf

script:
  - go test -race .
  - go test -covermode count -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out
  - codeclimate-test-reporter < cover.out
