sudo: false

language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps-test

install:
  - wget http://download.redis.io/releases/redis-stable.tar.gz
  - tar xf redis-stable.tar.gz
  - (cd redis-stable && make)
  - export PATH=./redis-stable/src:$PATH
  - redis ./travis/redis.conf

script:
  - make test
